jupyter nbconvert --to html  01-bayes.ipynb
jupyter nbconvert --to html  02-apriori.ipynb
jupyter nbconvert --to html  03-funciones-teoricas-probabilidad.ipynb
jupyter nbconvert --to html  04-analisis-exploratorio.ipynb
jupyter nbconvert --to html  05-pruebas-de-hipotesis.ipynb
jupyter nbconvert --to html  06-kmeans.ipynb
jupyter nbconvert --to html  07-knn.ipynb
jupyter nbconvert --to html  08-model-performance.ipynb
jupyter nbconvert --to html  09-linreg.ipynb
jupyter nbconvert --to html  10-regtree.ipynb
jupyter nbconvert --to html  11-logreg.ipynb
jupyter nbconvert --to html  12-OneR.ipynb
